<?php
return array (
  //==================================== Translations ====================================//
  'whisp_slider' => 'Whisp Slider',
  'instruction01' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">to create Event-1st go to setting to the right once you set up settings- Go to custom on right menu  test</span></span>',
  'instruction02' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">to Create a Event. go to-top left Button +Create Event Once you Create a event go to mange that Event Bellow</span></span>',
  'instruction03' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Once you set up custom page Go to Event on right Menu </span></span>',
  'instruction04' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Now you will see more right Menu Options go to right Menu Ticket and Make a Ticket you can Share your event on right of this page</span></span>',
  'instruction05' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Before Creating Ticket go to Customize right Menu then Go to Create Ticket top Left dark blue button and create ticket you will find a more options in Create ticket please explore many options-To edit ticket click on dark blue of ticket you created</span></span>',
  'instruction06' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Here you can refund & Cancel Ticket Cost,Resend ticket ,Print ticket, or edit user Details you also can export ticket Orders</span></span>',
  'instruction07' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Here you can Invite single Attendee or import list and invite Multiple Attendees print Export Or Message Attendees, you also here can Print PDF Ticket,edit, cancel,refund ticket, Search is at top Right</span></span>',
  'instruction08' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Once you Customize your Event then Go to Ticket on Right Menu</span></span>',
  'instruction09' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Please Check in Guests Here to leave this page you will need a pass code</span></span>',
  'instruction10' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Eric Instruction10</span></span>',
  'instruction11' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">Copy And Past this Code into your web site and you Members will have instant access to tickets </span></span>',
  'instruction12' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show"><span class="winstruction" style="cursor:pointer;">[hide]</span><span class="icontent show">create a code here for member access for free or discount tickets</span></span>',
);
?>