<?php
return array (
  //==================================== Translations ====================================//
  'instruction01' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">To create Event-1st go to USER SETTINGS on top right, once you set up  user settings go to ORGANIZER SETTING on left menu.<br> <span style="padding-left:25px;">
   Expired events and tickets will be saved for reusing and editing for future events.<br> <span style="padding-left:25px;">To see UPCOMING EVENTS , Go to your Event below. On that event it has Edit and Manage, Click on Manage to see more Menu items.</span></span>',
  'instruction02' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">To Create an Event, go to-top left Button. Click +Create Event.<br> <span style="padding-left:25px;">
   Once you Create your Event it should go directly to Ticket.  More menu options will appear on left.<br> <span style="padding-left:25px;">If not, To see more menu items on left,  Go to your Event below. On that event it has Edit and Manage, Click on Manage.</span></span>',
  'instruction03' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Once you set up ORGANIZER SETTINGS, Go to Event in Left Menu </span></span>',
  'instruction04' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Now you will see more left Menu Options. Make sure you look above at the option to publish this  Event. If not seen above it is Published. <br> <span style="padding-left:25px;"> On left menu click on Whisp Slider. There you can make an Event  Slider and  insert the event URL into  Slider. The URL is on Right of this page .<br> <span style="padding-left:25px;"> When you are ready, It is recommended to go to CUSTOMIZE EVENT 1st & then left Menu  to TICKET and create a Ticket<br> <span style="padding-left:25px;">On Right hand side of this page you have the ability to share your event Via URL / Facebook / Instagram, etc.</span></span>',
  'instruction05' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Before Creating a Ticket it is Recommended to go to Customize on left Menu,<br> <span style="padding-left:25px;">Then Go to Create Ticket. This Customize can be done at a later date if desired.<br> <span style="padding-left:25px;">There may be a few reasons to create more than one ticket. For example, <br> <span style="padding-left:25px;"> You have an Early ticket purchase option ( from & to ) date and a Full purchase ticket ( from & to ) date.Therefore make 2 Tickets.<br> <span style="padding-left:25px;"> Next If you have Couples, Single females, and Single males and each has their Own price. Therefore make 3 Tickets.<br> <span style="padding-left:25px;"> If you would like to Edit existing ticket, Click on dark blue header of ticket. These Tickets  can be edited &  Re-used for future Events</span></span>',
  'instruction06' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Here you can Refund, Cancel cost, Resend, and Print Tickets.<br> <span style="padding-left:25px;"> You can also Edit user details and Export ticket orders.</span></span>',
  'instruction07' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Here you can invite Single Attendee, Multiple Attendees or Import a list from invite Attendees. <br> <span style="padding-left:25px;">You can also Print, Export or Message Attendees, Print PDF ticket, Edit, Cancel or Refund ticket.<br> <span style="padding-left:25px;"> The Search bar for a Ticket holder is to the Right</span></span>',
  'instruction08' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Below you will find 7 new menu options to Customize this Event. Once you Customize your Event then Go to Ticket on Left Menu</span></span>',
  'instruction09' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;"></span><span class="icontent hide"><span style="padding-left:25px;">Please Check in your Guests Here!  To leave this page you will need a Pass Code</span></span>',
  'instruction10' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Here you can add questions which attendees will be asked to answer during the check-out process for their Ticket.</span></span>',
  'instruction11' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Copy And Paste this Code into your web site and your Members will have instant access to tickets. Look at example below on right</span></span>',
  'instruction12' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">Create a code here for member access for Free or Discount tickets, Then go to create ticket and Hide ticket  back and pick code from list.</span></span>',
'instruction13' => '<span style="padding-left:25px;"><span class="winstruction" style="cursor:pointer;">[Show Instructions]</span><span class="icontent hide"><span style="padding-left:25px;">here you can check to see what time a user has check in and out and back in again.</span></span>',
);
?>